kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-file-integrity

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- github.com/redhat-cop/gitops-catalog/file-integrity-operator/operator/overlays/release-0.1?ref=main