kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-compliance

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
- github.com/redhat-cop/gitops-catalog/compliance-operator/operator/overlays/stable?ref=main