apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: advanced-cluster-security
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/advanced-cluster-security/overlays/default
    repoURL: https://github.com/euanhume/infra-day-2023
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true