apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file-integrity-operator
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/file-integrity-operator/base
    repoURL: https://github.com/euanhume/infra-day-2023
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true