kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "1"

resources:
- github.com/redhat-cop/gitops-catalog/advanced-cluster-security-operator/aggregate/minimal?ref=main